### ISSUE TITLE
grub_background.png is the wrong format

### ISSUE THREAD

**Issue by shadeslayer** [netrunner-artwork/artwork-grub-theme-netrunner-neo#1]
![image](https://cloud.githubusercontent.com/assets/188976/17960984/6e696a8a-6aa9-11e6-8b87-a682792d4a75.png)

**Comment by UriHerrera** [comment]
I'm positive it supports it:
![](http://i.imgur.com/wv55Bfw.png)

And that it's also a PNG image:
![](http://i.imgur.com/VgD4CiN.png)

> TriD is a tool to check mimetypes on Windows.

# 

No idea why QEMU says that.

**Comment by shadeslayer** [comment]
Right, fixed it, grub was being weird :)
